-file("/Users/jake/erlinstalls/19.0/lib/parsetools-2.1.2/include/leexinc.hrl", 0).
%% The source of this file is part of leex distribution, as such it
%% has the same Copyright as the other files in the leex
%% distribution. The Copyright is defined in the accompanying file
%% COPYRIGHT. However, the resultant scanner generated by leex is the
%% property of the creator of the scanner and is not covered by that
%% Copyright.

-module(tokens).

-export([string/1,string/2,token/2,token/3,tokens/2,tokens/3]).
-export([format_error/1]).

%% User code. This is placed here to allow extra attributes.
-file("src/tokens.xrl", 95).

-file("/Users/jake/erlinstalls/19.0/lib/parsetools-2.1.2/include/leexinc.hrl", 14).

format_error({illegal,S}) -> ["illegal characters ",io_lib:write_string(S)];
format_error({user,S}) -> S.

string(String) -> string(String, 1).

string(String, Line) -> string(String, Line, String, []).

%% string(InChars, Line, TokenChars, Tokens) ->
%% {ok,Tokens,Line} | {error,ErrorInfo,Line}.
%% Note the line number going into yystate, L0, is line of token
%% start while line number returned is line of token end. We want line
%% of token start.

string([], L, [], Ts) ->                     % No partial tokens!
    {ok,yyrev(Ts),L};
string(Ics0, L0, Tcs, Ts) ->
    case yystate(yystate(), Ics0, L0, 0, reject, 0) of
        {A,Alen,Ics1,L1} ->                  % Accepting end state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {A,Alen,Ics1,L1,_S1} ->              % Accepting transistion state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {reject,_Alen,Tlen,_Ics1,L1,_S1} ->  % After a non-accepting state
            {error,{L0,?MODULE,{illegal,yypre(Tcs, Tlen+1)}},L1};
        {A,Alen,_Tlen,_Ics1,_L1,_S1} ->
            string_cont(yysuf(Tcs, Alen), L0, yyaction(A, Alen, Tcs, L0), Ts)
    end.

%% string_cont(RestChars, Line, Token, Tokens)
%% Test for and remove the end token wrapper. Push back characters
%% are prepended to RestChars.

-dialyzer({nowarn_function, string_cont/4}).

string_cont(Rest, Line, {token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, {end_token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, skip_token, Ts) ->
    string(Rest, Line, Rest, Ts);
string_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, Ts);
string_cont(_Rest, Line, {error,S}, _Ts) ->
    {error,{Line,?MODULE,{user,S}},Line}.

%% token(Continuation, Chars) ->
%% token(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {token,State,CurrLine,TokenChars,TokenLen,TokenLine,AccAction,AccLen}

token(Cont, Chars) -> token(Cont, Chars, 1).

token([], Chars, Line) ->
    token(yystate(), Chars, Line, Chars, 0, Line, reject, 0);
token({token,State,Line,Tcs,Tlen,Tline,Action,Alen}, Chars, _) ->
    token(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Action, Alen).

%% token(State, InChars, Line, TokenChars, TokenLen, TokenLine,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% The argument order is chosen to be more efficient.

token(S0, Ics0, L0, Tcs, Tlen0, Tline, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{token,S1,L1,Tcs,Alen1,Tline,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{token,S1,L1,Tcs,Tlen1,Tline,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     true -> {eof,L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,Ics1,L1,_S1} ->    % No token match
            Error = {Tline,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            {done,{error,Error,L1},Ics1};
        {A1,Alen1,_Tlen1,_Ics1,_L1,_S1} ->       % Use last accept match
            token_cont(yysuf(Tcs, Alen1), L0, yyaction(A1, Alen1, Tcs, Tline))
    end.

%% token_cont(RestChars, Line, Token)
%% If we have a token or error then return done, else if we have a
%% skip_token then continue.

-dialyzer({nowarn_function, token_cont/3}).

token_cont(Rest, Line, {token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, {end_token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {end_token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, skip_token) ->
    token(yystate(), Rest, Line, Rest, 0, Line, reject, 0);
token_cont(Rest, Line, {skip_token,Push}) ->
    NewRest = Push ++ Rest,
    token(yystate(), NewRest, Line, NewRest, 0, Line, reject, 0);
token_cont(Rest, Line, {error,S}) ->
    {done,{error,{Line,?MODULE,{user,S}},Line},Rest}.

%% tokens(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Tokens,AccAction,AccLen}
%% {skip_tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Error,AccAction,AccLen}

tokens(Cont, Chars) -> tokens(Cont, Chars, 1).

tokens([], Chars, Line) ->
    tokens(yystate(), Chars, Line, Chars, 0, Line, [], reject, 0);
tokens({tokens,State,Line,Tcs,Tlen,Tline,Ts,Action,Alen}, Chars, _) ->
    tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Ts, Action, Alen);
tokens({skip_tokens,State,Line,Tcs,Tlen,Tline,Error,Action,Alen}, Chars, _) ->
    skip_tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Error, Action, Alen).

%% tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Ts, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Alen1,Tline,Ts,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Tlen1,Tline,Ts,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error, no need to skip here.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     Ts == [] -> {eof,L1};
                     true -> {ok,yyrev(Ts),L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            %% Skip rest of tokens.
            Error = {L1,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,_Tlen1,_Ics1,_L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            tokens_cont(yysuf(Tcs, Alen1), L0, Token, Ts)
    end.

%% tokens_cont(RestChars, Line, Token, Tokens)
%% If we have an end_token or error then return done, else if we have
%% a token then save it and continue, else if we have a skip_token
%% just continue.

-dialyzer({nowarn_function, tokens_cont/4}).

tokens_cont(Rest, Line, {token,T}, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {end_token,T}, Ts) ->
    {done,{ok,yyrev(Ts, [T]),Line},Rest};
tokens_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    {done,{ok,yyrev(Ts, [T]),Line},NewRest};
tokens_cont(Rest, Line, skip_token, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {error,S}, _Ts) ->
    skip_tokens(Rest, Line, {Line,?MODULE,{user,S}}).

%%skip_tokens(InChars, Line, Error) -> {done,{error,Error,Line},Ics}.
%% Skip tokens until an end token, junk everything and return the error.

skip_tokens(Ics, Line, Error) ->
    skip_tokens(yystate(), Ics, Line, Ics, 0, Line, Error, reject, 0).

%% skip_tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

skip_tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Error, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        {A1,Alen1,Ics1,L1} ->                  % Accepting end state
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,[],L1,S1} ->                 % After an accepting state
            {more,{skip_tokens,S1,L1,Tcs,Alen1,Tline,Error,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,Tlen1,[],L1,S1} ->           % After a non-accepting state
            {more,{skip_tokens,S1,L1,Tcs,Tlen1,Tline,Error,A1,Alen1}};
        {reject,_Alen1,_Tlen1,eof,L1,_S1} ->
            {done,{error,Error,L1},eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,_Tlen1,_Ics1,L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            skip_cont(yysuf(Tcs, Alen1), L1, Token, Error)
    end.

%% skip_cont(RestChars, Line, Token, Error)
%% Skip tokens until we have an end_token or error then return done
%% with the original rror.

-dialyzer({nowarn_function, skip_cont/4}).

skip_cont(Rest, Line, {token,_T}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {end_token,_T}, Error) ->
    {done,{error,Error,Line},Rest};
skip_cont(Rest, Line, {end_token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    {done,{error,Error,Line},NewRest};
skip_cont(Rest, Line, skip_token, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {skip_token,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {error,_S}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0).

yyrev(List) -> lists:reverse(List).
yyrev(List, Tail) -> lists:reverse(List, Tail).
yypre(List, N) -> lists:sublist(List, N).
yysuf(List, N) -> lists:nthtail(N, List).

%% yystate() -> InitialState.
%% yystate(State, InChars, Line, CurrTokLen, AcceptAction, AcceptLen) ->
%% {Action, AcceptLen, RestChars, Line} |
%% {Action, AcceptLen, RestChars, Line, State} |
%% {reject, AcceptLen, CurrTokLen, RestChars, Line, State} |
%% {Action, AcceptLen, CurrTokLen, RestChars, Line, State}.
%% Generated state transition functions. The non-accepting end state
%% return signal either an unrecognised character or end of current
%% input.

-file("src/tokens.erl", 284).
yystate() -> 159.

yystate(162, [82|Ics], Line, Tlen, _, _) ->
    yystate(158, Ics, Line, Tlen+1, 38, Tlen);
yystate(162, [80|Ics], Line, Tlen, _, _) ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(162, [81|Ics], Line, Tlen, _, _) ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(162, [79|Ics], Line, Tlen, _, _) ->
    yystate(126, Ics, Line, Tlen+1, 38, Tlen);
yystate(162, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(162, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 78 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(162, [C|Ics], Line, Tlen, _, _) when C >= 83, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(162, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,162};
yystate(161, [32|Ics], Line, Tlen, _, _) ->
    yystate(161, Ics, Line, Tlen+1, 37, Tlen);
yystate(161, [13|Ics], Line, Tlen, _, _) ->
    yystate(161, Ics, Line, Tlen+1, 37, Tlen);
yystate(161, [9|Ics], Line, Tlen, _, _) ->
    yystate(161, Ics, Line, Tlen+1, 37, Tlen);
yystate(161, Ics, Line, Tlen, _, _) ->
    {37,Tlen,Ics,Line,161};
yystate(160, Ics, Line, Tlen, _, _) ->
    {8,Tlen,Ics,Line};
yystate(159, [87|Ics], Line, Tlen, Action, Alen) ->
    yystate(155, Ics, Line, Tlen+1, Action, Alen);
yystate(159, [85|Ics], Line, Tlen, Action, Alen) ->
    yystate(55, Ics, Line, Tlen+1, Action, Alen);
yystate(159, [86|Ics], Line, Tlen, Action, Alen) ->
    yystate(55, Ics, Line, Tlen+1, Action, Alen);
yystate(159, [84|Ics], Line, Tlen, Action, Alen) ->
    yystate(51, Ics, Line, Tlen+1, Action, Alen);
yystate(159, [83|Ics], Line, Tlen, Action, Alen) ->
    yystate(43, Ics, Line, Tlen+1, Action, Alen);
yystate(159, [82|Ics], Line, Tlen, Action, Alen) ->
    yystate(23, Ics, Line, Tlen+1, Action, Alen);
yystate(159, [81|Ics], Line, Tlen, Action, Alen) ->
    yystate(55, Ics, Line, Tlen+1, Action, Alen);
yystate(159, [80|Ics], Line, Tlen, Action, Alen) ->
    yystate(84, Ics, Line, Tlen+1, Action, Alen);
yystate(159, [73|Ics], Line, Tlen, Action, Alen) ->
    yystate(136, Ics, Line, Tlen+1, Action, Alen);
yystate(159, [72|Ics], Line, Tlen, Action, Alen) ->
    yystate(55, Ics, Line, Tlen+1, Action, Alen);
yystate(159, [71|Ics], Line, Tlen, Action, Alen) ->
    yystate(144, Ics, Line, Tlen+1, Action, Alen);
yystate(159, [70|Ics], Line, Tlen, Action, Alen) ->
    yystate(162, Ics, Line, Tlen+1, Action, Alen);
yystate(159, [69|Ics], Line, Tlen, Action, Alen) ->
    yystate(106, Ics, Line, Tlen+1, Action, Alen);
yystate(159, [68|Ics], Line, Tlen, Action, Alen) ->
    yystate(34, Ics, Line, Tlen+1, Action, Alen);
yystate(159, [67|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(159, [66|Ics], Line, Tlen, Action, Alen) ->
    yystate(37, Ics, Line, Tlen+1, Action, Alen);
yystate(159, [65|Ics], Line, Tlen, Action, Alen) ->
    yystate(73, Ics, Line, Tlen+1, Action, Alen);
yystate(159, [61|Ics], Line, Tlen, Action, Alen) ->
    yystate(97, Ics, Line, Tlen+1, Action, Alen);
yystate(159, [47|Ics], Line, Tlen, Action, Alen) ->
    yystate(121, Ics, Line, Tlen+1, Action, Alen);
yystate(159, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(125, Ics, Line, Tlen+1, Action, Alen);
yystate(159, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(133, Ics, Line, Tlen+1, Action, Alen);
yystate(159, [44|Ics], Line, Tlen, Action, Alen) ->
    yystate(137, Ics, Line, Tlen+1, Action, Alen);
yystate(159, [43|Ics], Line, Tlen, Action, Alen) ->
    yystate(141, Ics, Line, Tlen+1, Action, Alen);
yystate(159, [42|Ics], Line, Tlen, Action, Alen) ->
    yystate(145, Ics, Line, Tlen+1, Action, Alen);
yystate(159, [41|Ics], Line, Tlen, Action, Alen) ->
    yystate(149, Ics, Line, Tlen+1, Action, Alen);
yystate(159, [40|Ics], Line, Tlen, Action, Alen) ->
    yystate(153, Ics, Line, Tlen+1, Action, Alen);
yystate(159, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(161, Ics, Line, Tlen+1, Action, Alen);
yystate(159, [13|Ics], Line, Tlen, Action, Alen) ->
    yystate(161, Ics, Line, Tlen+1, Action, Alen);
yystate(159, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(157, Ics, Line+1, Tlen+1, Action, Alen);
yystate(159, [9|Ics], Line, Tlen, Action, Alen) ->
    yystate(161, Ics, Line, Tlen+1, Action, Alen);
yystate(159, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(101, Ics, Line, Tlen+1, Action, Alen);
yystate(159, [C|Ics], Line, Tlen, Action, Alen) when C >= 74, C =< 79 ->
    yystate(55, Ics, Line, Tlen+1, Action, Alen);
yystate(159, [C|Ics], Line, Tlen, Action, Alen) when C >= 88, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, Action, Alen);
yystate(159, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,159};
yystate(158, [69|Ics], Line, Tlen, _, _) ->
    yystate(154, Ics, Line, Tlen+1, 38, Tlen);
yystate(158, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(158, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 68 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(158, [C|Ics], Line, Tlen, _, _) when C >= 70, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(158, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,158};
yystate(157, Ics, Line, Tlen, _, _) ->
    {36,Tlen,Ics,Line};
yystate(156, [79|Ics], Line, Tlen, Action, Alen) ->
    yystate(160, Ics, Line, Tlen+1, Action, Alen);
yystate(156, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,156};
yystate(155, [82|Ics], Line, Tlen, _, _) ->
    yystate(151, Ics, Line, Tlen+1, 38, Tlen);
yystate(155, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(155, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 81 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(155, [C|Ics], Line, Tlen, _, _) when C >= 83, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(155, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,155};
yystate(154, [81|Ics], Line, Tlen, _, _) ->
    yystate(150, Ics, Line, Tlen+1, 38, Tlen);
yystate(154, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(154, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 80 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(154, [C|Ics], Line, Tlen, _, _) when C >= 82, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(154, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,154};
yystate(153, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line};
yystate(152, [84|Ics], Line, Tlen, Action, Alen) ->
    yystate(156, Ics, Line, Tlen+1, Action, Alen);
yystate(152, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,152};
yystate(151, [73|Ics], Line, Tlen, _, _) ->
    yystate(147, Ics, Line, Tlen+1, 38, Tlen);
yystate(151, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(151, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 72 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(151, [C|Ics], Line, Tlen, _, _) when C >= 74, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(151, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,151};
yystate(150, [85|Ics], Line, Tlen, _, _) ->
    yystate(146, Ics, Line, Tlen+1, 38, Tlen);
yystate(150, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(150, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 84 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(150, [C|Ics], Line, Tlen, _, _) when C >= 86, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(150, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,150};
yystate(149, Ics, Line, Tlen, _, _) ->
    {0,Tlen,Ics,Line};
yystate(148, [32|Ics], Line, Tlen, _, _) ->
    yystate(152, Ics, Line, Tlen+1, 38, Tlen);
yystate(148, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(148, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(148, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,148};
yystate(147, [84|Ics], Line, Tlen, _, _) ->
    yystate(143, Ics, Line, Tlen+1, 38, Tlen);
yystate(147, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(147, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 83 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(147, [C|Ics], Line, Tlen, _, _) when C >= 85, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(147, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,147};
yystate(146, [69|Ics], Line, Tlen, _, _) ->
    yystate(142, Ics, Line, Tlen+1, 38, Tlen);
yystate(146, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(146, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 68 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(146, [C|Ics], Line, Tlen, _, _) when C >= 70, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(146, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,146};
yystate(145, Ics, Line, Tlen, _, _) ->
    {33,Tlen,Ics,Line};
yystate(144, [79|Ics], Line, Tlen, _, _) ->
    yystate(148, Ics, Line, Tlen+1, 38, Tlen);
yystate(144, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(144, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 78 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(144, [C|Ics], Line, Tlen, _, _) when C >= 80, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(144, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,144};
yystate(143, [69|Ics], Line, Tlen, _, _) ->
    yystate(139, Ics, Line, Tlen+1, 38, Tlen);
yystate(143, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(143, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 68 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(143, [C|Ics], Line, Tlen, _, _) when C >= 70, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(143, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,143};
yystate(142, [78|Ics], Line, Tlen, _, _) ->
    yystate(138, Ics, Line, Tlen+1, 38, Tlen);
yystate(142, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(142, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 77 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(142, [C|Ics], Line, Tlen, _, _) when C >= 79, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(142, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,142};
yystate(141, [46|Ics], Line, Tlen, _, _) ->
    yystate(125, Ics, Line, Tlen+1, 32, Tlen);
yystate(141, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(101, Ics, Line, Tlen+1, 32, Tlen);
yystate(141, Ics, Line, Tlen, _, _) ->
    {32,Tlen,Ics,Line,141};
yystate(140, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 7, Tlen);
yystate(140, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 7, Tlen);
yystate(140, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,140};
yystate(139, [32|Ics], Line, Tlen, _, _) ->
    yystate(135, Ics, Line, Tlen+1, 15, Tlen);
yystate(139, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 15, Tlen);
yystate(139, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 15, Tlen);
yystate(139, Ics, Line, Tlen, _, _) ->
    {15,Tlen,Ics,Line,139};
yystate(138, [67|Ics], Line, Tlen, _, _) ->
    yystate(134, Ics, Line, Tlen+1, 38, Tlen);
yystate(138, [65|Ics], Line, Tlen, _, _) ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(138, [66|Ics], Line, Tlen, _, _) ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(138, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(138, [C|Ics], Line, Tlen, _, _) when C >= 68, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(138, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,138};
yystate(137, Ics, Line, Tlen, _, _) ->
    {2,Tlen,Ics,Line};
yystate(136, [70|Ics], Line, Tlen, _, _) ->
    yystate(140, Ics, Line, Tlen+1, 38, Tlen);
yystate(136, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(136, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 69 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(136, [C|Ics], Line, Tlen, _, _) when C >= 71, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(136, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,136};
yystate(135, [84|Ics], Line, Tlen, Action, Alen) ->
    yystate(131, Ics, Line, Tlen+1, Action, Alen);
yystate(135, [79|Ics], Line, Tlen, Action, Alen) ->
    yystate(115, Ics, Line, Tlen+1, Action, Alen);
yystate(135, [68|Ics], Line, Tlen, Action, Alen) ->
    yystate(71, Ics, Line, Tlen+1, Action, Alen);
yystate(135, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,135};
yystate(134, [90|Ics], Line, Tlen, _, _) ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(134, [89|Ics], Line, Tlen, _, _) ->
    yystate(130, Ics, Line, Tlen+1, 38, Tlen);
yystate(134, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(134, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 88 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(134, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,134};
yystate(133, [46|Ics], Line, Tlen, _, _) ->
    yystate(125, Ics, Line, Tlen+1, 35, Tlen);
yystate(133, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(101, Ics, Line, Tlen+1, 35, Tlen);
yystate(133, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,133};
yystate(132, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 26, Tlen);
yystate(132, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 26, Tlen);
yystate(132, Ics, Line, Tlen, _, _) ->
    {26,Tlen,Ics,Line,132};
yystate(131, [65|Ics], Line, Tlen, Action, Alen) ->
    yystate(127, Ics, Line, Tlen+1, Action, Alen);
yystate(131, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,131};
yystate(130, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 29, Tlen);
yystate(130, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 29, Tlen);
yystate(130, Ics, Line, Tlen, _, _) ->
    {29,Tlen,Ics,Line,130};
yystate(129, [69|Ics], Line, Tlen, _, _) ->
    yystate(105, Ics, Line, Tlen+1, 3, Tlen);
yystate(129, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(129, Ics, Line, Tlen+1, 3, Tlen);
yystate(129, Ics, Line, Tlen, _, _) ->
    {3,Tlen,Ics,Line,129};
yystate(128, [69|Ics], Line, Tlen, _, _) ->
    yystate(132, Ics, Line, Tlen+1, 38, Tlen);
yystate(128, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(128, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 68 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(128, [C|Ics], Line, Tlen, _, _) when C >= 70, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(128, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,128};
yystate(127, [80|Ics], Line, Tlen, Action, Alen) ->
    yystate(123, Ics, Line, Tlen+1, Action, Alen);
yystate(127, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,127};
yystate(126, [82|Ics], Line, Tlen, _, _) ->
    yystate(122, Ics, Line, Tlen+1, 38, Tlen);
yystate(126, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(126, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 81 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(126, [C|Ics], Line, Tlen, _, _) when C >= 83, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(126, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,126};
yystate(125, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(129, Ics, Line, Tlen+1, Action, Alen);
yystate(125, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,125};
yystate(124, [83|Ics], Line, Tlen, _, _) ->
    yystate(128, Ics, Line, Tlen+1, 38, Tlen);
yystate(124, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(124, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 82 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(124, [C|Ics], Line, Tlen, _, _) when C >= 84, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(124, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,124};
yystate(123, [69|Ics], Line, Tlen, Action, Alen) ->
    yystate(119, Ics, Line, Tlen+1, Action, Alen);
yystate(123, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,123};
yystate(122, [77|Ics], Line, Tlen, _, _) ->
    yystate(118, Ics, Line, Tlen+1, 38, Tlen);
yystate(122, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(122, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 76 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(122, [C|Ics], Line, Tlen, _, _) when C >= 78, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(122, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,122};
yystate(121, Ics, Line, Tlen, _, _) ->
    {34,Tlen,Ics,Line};
yystate(120, [85|Ics], Line, Tlen, _, _) ->
    yystate(124, Ics, Line, Tlen+1, 38, Tlen);
yystate(120, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(120, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 84 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(120, [C|Ics], Line, Tlen, _, _) when C >= 86, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(120, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,120};
yystate(119, Ics, Line, Tlen, _, _) ->
    {21,Tlen,Ics,Line};
yystate(118, [65|Ics], Line, Tlen, _, _) ->
    yystate(114, Ics, Line, Tlen+1, 38, Tlen);
yystate(118, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(118, [C|Ics], Line, Tlen, _, _) when C >= 66, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(118, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,118};
yystate(117, [69|Ics], Line, Tlen, _, _) ->
    yystate(105, Ics, Line, Tlen+1, 3, Tlen);
yystate(117, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(117, Ics, Line, Tlen+1, 3, Tlen);
yystate(117, Ics, Line, Tlen, _, _) ->
    {3,Tlen,Ics,Line,117};
yystate(116, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 17, Tlen);
yystate(116, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 17, Tlen);
yystate(116, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,116};
yystate(115, [85|Ics], Line, Tlen, Action, Alen) ->
    yystate(111, Ics, Line, Tlen+1, Action, Alen);
yystate(115, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,115};
yystate(114, [84|Ics], Line, Tlen, _, _) ->
    yystate(110, Ics, Line, Tlen+1, 38, Tlen);
yystate(114, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(114, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 83 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(114, [C|Ics], Line, Tlen, _, _) when C >= 85, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(114, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,114};
yystate(113, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(109, Ics, Line, Tlen+1, Action, Alen);
yystate(113, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,113};
yystate(112, [84|Ics], Line, Tlen, _, _) ->
    yystate(116, Ics, Line, Tlen+1, 38, Tlen);
yystate(112, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(112, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 83 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(112, [C|Ics], Line, Tlen, _, _) when C >= 85, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(112, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,112};
yystate(111, [84|Ics], Line, Tlen, Action, Alen) ->
    yystate(107, Ics, Line, Tlen+1, Action, Alen);
yystate(111, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,111};
yystate(110, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 12, Tlen);
yystate(110, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 12, Tlen);
yystate(110, Ics, Line, Tlen, _, _) ->
    {12,Tlen,Ics,Line,110};
yystate(109, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(109, Ics, Line, Tlen+1, 3, Tlen);
yystate(109, Ics, Line, Tlen, _, _) ->
    {3,Tlen,Ics,Line,109};
yystate(108, [78|Ics], Line, Tlen, _, _) ->
    yystate(112, Ics, Line, Tlen+1, 38, Tlen);
yystate(108, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(108, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 77 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(108, [C|Ics], Line, Tlen, _, _) when C >= 79, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(108, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,108};
yystate(107, [80|Ics], Line, Tlen, Action, Alen) ->
    yystate(103, Ics, Line, Tlen+1, Action, Alen);
yystate(107, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,107};
yystate(106, [81|Ics], Line, Tlen, _, _) ->
    yystate(102, Ics, Line, Tlen+1, 38, Tlen);
yystate(106, [79|Ics], Line, Tlen, _, _) ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(106, [80|Ics], Line, Tlen, _, _) ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(106, [78|Ics], Line, Tlen, _, _) ->
    yystate(62, Ics, Line, Tlen+1, 38, Tlen);
yystate(106, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(106, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 77 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(106, [C|Ics], Line, Tlen, _, _) when C >= 82, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(106, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,106};
yystate(105, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(113, Ics, Line, Tlen+1, Action, Alen);
yystate(105, [43|Ics], Line, Tlen, Action, Alen) ->
    yystate(113, Ics, Line, Tlen+1, Action, Alen);
yystate(105, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(109, Ics, Line, Tlen+1, Action, Alen);
yystate(105, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,105};
yystate(104, [73|Ics], Line, Tlen, _, _) ->
    yystate(108, Ics, Line, Tlen+1, 38, Tlen);
yystate(104, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(104, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 72 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(104, [C|Ics], Line, Tlen, _, _) when C >= 74, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(104, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,104};
yystate(103, [85|Ics], Line, Tlen, Action, Alen) ->
    yystate(99, Ics, Line, Tlen+1, Action, Alen);
yystate(103, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,103};
yystate(102, [85|Ics], Line, Tlen, _, _) ->
    yystate(98, Ics, Line, Tlen+1, 38, Tlen);
yystate(102, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(102, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 84 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(102, [C|Ics], Line, Tlen, _, _) when C >= 86, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(102, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,102};
yystate(101, [46|Ics], Line, Tlen, _, _) ->
    yystate(117, Ics, Line, Tlen+1, 4, Tlen);
yystate(101, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(101, Ics, Line, Tlen+1, 4, Tlen);
yystate(101, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,101};
yystate(100, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 18, Tlen);
yystate(100, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 18, Tlen);
yystate(100, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,100};
yystate(99, [84|Ics], Line, Tlen, Action, Alen) ->
    yystate(95, Ics, Line, Tlen+1, Action, Alen);
yystate(99, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,99};
yystate(98, [73|Ics], Line, Tlen, _, _) ->
    yystate(94, Ics, Line, Tlen+1, 38, Tlen);
yystate(98, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(98, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 72 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(98, [C|Ics], Line, Tlen, _, _) when C >= 74, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(98, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,98};
yystate(97, Ics, Line, Tlen, _, _) ->
    {31,Tlen,Ics,Line};
yystate(96, [72|Ics], Line, Tlen, _, _) ->
    yystate(100, Ics, Line, Tlen+1, 38, Tlen);
yystate(96, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(96, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 71 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(96, [C|Ics], Line, Tlen, _, _) when C >= 73, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(96, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,96};
yystate(95, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(91, Ics, Line, Tlen+1, Action, Alen);
yystate(95, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,95};
yystate(94, [86|Ics], Line, Tlen, _, _) ->
    yystate(90, Ics, Line, Tlen+1, 38, Tlen);
yystate(94, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(94, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 85 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(94, [C|Ics], Line, Tlen, _, _) when C >= 87, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(94, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,94};
yystate(93, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 9, Tlen);
yystate(93, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 9, Tlen);
yystate(93, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,93};
yystate(92, [67|Ics], Line, Tlen, _, _) ->
    yystate(96, Ics, Line, Tlen+1, 38, Tlen);
yystate(92, [65|Ics], Line, Tlen, _, _) ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(92, [66|Ics], Line, Tlen, _, _) ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(92, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(92, [C|Ics], Line, Tlen, _, _) when C >= 68, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(92, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,92};
yystate(91, [84|Ics], Line, Tlen, Action, Alen) ->
    yystate(87, Ics, Line, Tlen+1, Action, Alen);
yystate(91, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,91};
yystate(90, [65|Ics], Line, Tlen, _, _) ->
    yystate(86, Ics, Line, Tlen+1, 38, Tlen);
yystate(90, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(90, [C|Ics], Line, Tlen, _, _) when C >= 66, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(90, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,90};
yystate(89, [78|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 38, Tlen);
yystate(89, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(89, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 77 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(89, [C|Ics], Line, Tlen, _, _) when C >= 79, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(89, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,89};
yystate(88, [78|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 38, Tlen);
yystate(88, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(88, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 77 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(88, [C|Ics], Line, Tlen, _, _) when C >= 79, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(88, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,88};
yystate(87, [65|Ics], Line, Tlen, Action, Alen) ->
    yystate(83, Ics, Line, Tlen+1, Action, Alen);
yystate(87, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,87};
yystate(86, [76|Ics], Line, Tlen, _, _) ->
    yystate(82, Ics, Line, Tlen+1, 38, Tlen);
yystate(86, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(86, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 75 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(86, [C|Ics], Line, Tlen, _, _) when C >= 77, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(86, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,86};
yystate(85, [71|Ics], Line, Tlen, _, _) ->
    yystate(89, Ics, Line, Tlen+1, 38, Tlen);
yystate(85, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(85, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 70 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(85, [C|Ics], Line, Tlen, _, _) when C >= 72, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(85, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,85};
yystate(84, [85|Ics], Line, Tlen, _, _) ->
    yystate(88, Ics, Line, Tlen+1, 38, Tlen);
yystate(84, [83|Ics], Line, Tlen, _, _) ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(84, [84|Ics], Line, Tlen, _, _) ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(84, [82|Ics], Line, Tlen, _, _) ->
    yystate(104, Ics, Line, Tlen+1, 38, Tlen);
yystate(84, [65|Ics], Line, Tlen, _, _) ->
    yystate(120, Ics, Line, Tlen+1, 38, Tlen);
yystate(84, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(84, [C|Ics], Line, Tlen, _, _) when C >= 66, C =< 81 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(84, [C|Ics], Line, Tlen, _, _) when C >= 86, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(84, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,84};
yystate(83, [80|Ics], Line, Tlen, Action, Alen) ->
    yystate(79, Ics, Line, Tlen+1, Action, Alen);
yystate(83, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,83};
yystate(82, [69|Ics], Line, Tlen, _, _) ->
    yystate(78, Ics, Line, Tlen+1, 38, Tlen);
yystate(82, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(82, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 68 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(82, [C|Ics], Line, Tlen, _, _) when C >= 70, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(82, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,82};
yystate(81, [73|Ics], Line, Tlen, _, _) ->
    yystate(85, Ics, Line, Tlen+1, 38, Tlen);
yystate(81, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(81, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 72 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(81, [C|Ics], Line, Tlen, _, _) when C >= 74, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(81, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,81};
yystate(80, Ics, Line, Tlen, _, _) ->
    {20,Tlen,Ics,Line};
yystate(79, [69|Ics], Line, Tlen, Action, Alen) ->
    yystate(75, Ics, Line, Tlen+1, Action, Alen);
yystate(79, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,79};
yystate(78, [78|Ics], Line, Tlen, _, _) ->
    yystate(74, Ics, Line, Tlen+1, 38, Tlen);
yystate(78, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(78, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 77 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(78, [C|Ics], Line, Tlen, _, _) when C >= 79, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(78, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,78};
yystate(77, [83|Ics], Line, Tlen, _, _) ->
    yystate(81, Ics, Line, Tlen+1, 38, Tlen);
yystate(77, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(77, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 82 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(77, [C|Ics], Line, Tlen, _, _) when C >= 84, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(77, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,77};
yystate(76, [77|Ics], Line, Tlen, Action, Alen) ->
    yystate(80, Ics, Line, Tlen+1, Action, Alen);
yystate(76, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,76};
yystate(75, Ics, Line, Tlen, _, _) ->
    {16,Tlen,Ics,Line};
yystate(74, [67|Ics], Line, Tlen, _, _) ->
    yystate(70, Ics, Line, Tlen+1, 38, Tlen);
yystate(74, [65|Ics], Line, Tlen, _, _) ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(74, [66|Ics], Line, Tlen, _, _) ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(74, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(74, [C|Ics], Line, Tlen, _, _) when C >= 68, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(74, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,74};
yystate(73, [83|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 38, Tlen);
yystate(73, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(73, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 82 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(73, [C|Ics], Line, Tlen, _, _) when C >= 84, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(73, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,73};
yystate(72, [85|Ics], Line, Tlen, Action, Alen) ->
    yystate(76, Ics, Line, Tlen+1, Action, Alen);
yystate(72, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,72};
yystate(71, [82|Ics], Line, Tlen, Action, Alen) ->
    yystate(67, Ics, Line, Tlen+1, Action, Alen);
yystate(71, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,71};
yystate(70, [69|Ics], Line, Tlen, _, _) ->
    yystate(66, Ics, Line, Tlen+1, 38, Tlen);
yystate(70, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(70, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 68 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(70, [C|Ics], Line, Tlen, _, _) when C >= 70, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(70, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,70};
yystate(69, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 25, Tlen);
yystate(69, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 25, Tlen);
yystate(69, Ics, Line, Tlen, _, _) ->
    {25,Tlen,Ics,Line,69};
yystate(68, [82|Ics], Line, Tlen, Action, Alen) ->
    yystate(72, Ics, Line, Tlen+1, Action, Alen);
yystate(68, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,68};
yystate(67, [85|Ics], Line, Tlen, Action, Alen) ->
    yystate(63, Ics, Line, Tlen+1, Action, Alen);
yystate(67, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,67};
yystate(66, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 6, Tlen);
yystate(66, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 6, Tlen);
yystate(66, Ics, Line, Tlen, _, _) ->
    {6,Tlen,Ics,Line,66};
yystate(65, [69|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 38, Tlen);
yystate(65, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(65, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 68 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(65, [C|Ics], Line, Tlen, _, _) when C >= 70, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(65, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,65};
yystate(64, Ics, Line, Tlen, _, _) ->
    {14,Tlen,Ics,Line};
yystate(63, [77|Ics], Line, Tlen, Action, Alen) ->
    yystate(59, Ics, Line, Tlen+1, Action, Alen);
yystate(63, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,63};
yystate(62, [68|Ics], Line, Tlen, _, _) ->
    yystate(58, Ics, Line, Tlen+1, 38, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 67 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 69, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(62, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,62};
yystate(61, [67|Ics], Line, Tlen, _, _) ->
    yystate(65, Ics, Line, Tlen+1, 38, Tlen);
yystate(61, [65|Ics], Line, Tlen, _, _) ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(61, [66|Ics], Line, Tlen, _, _) ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(61, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(61, [C|Ics], Line, Tlen, _, _) when C >= 68, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(61, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,61};
yystate(60, [69|Ics], Line, Tlen, Action, Alen) ->
    yystate(64, Ics, Line, Tlen+1, Action, Alen);
yystate(60, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,60};
yystate(59, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line};
yystate(58, [32|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 38, Tlen);
yystate(58, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(58, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(58, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,58};
yystate(57, [65|Ics], Line, Tlen, _, _) ->
    yystate(61, Ics, Line, Tlen+1, 38, Tlen);
yystate(57, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(57, [C|Ics], Line, Tlen, _, _) when C >= 66, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(57, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,57};
yystate(56, [80|Ics], Line, Tlen, Action, Alen) ->
    yystate(60, Ics, Line, Tlen+1, Action, Alen);
yystate(56, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,56};
yystate(55, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(55, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(55, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,55};
yystate(54, [70|Ics], Line, Tlen, Action, Alen) ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(54, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,54};
yystate(53, [80|Ics], Line, Tlen, _, _) ->
    yystate(57, Ics, Line, Tlen+1, 38, Tlen);
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 79 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= 81, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(53, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,53};
yystate(52, [65|Ics], Line, Tlen, Action, Alen) ->
    yystate(56, Ics, Line, Tlen+1, Action, Alen);
yystate(52, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,52};
yystate(51, [79|Ics], Line, Tlen, _, _) ->
    yystate(47, Ics, Line, Tlen+1, 38, Tlen);
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 78 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= 80, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(51, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,51};
yystate(50, [73|Ics], Line, Tlen, Action, Alen) ->
    yystate(46, Ics, Line, Tlen+1, Action, Alen);
yystate(50, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,50};
yystate(49, [83|Ics], Line, Tlen, _, _) ->
    yystate(53, Ics, Line, Tlen+1, 38, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 82 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 84, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(49, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,49};
yystate(48, [84|Ics], Line, Tlen, Action, Alen) ->
    yystate(52, Ics, Line, Tlen+1, Action, Alen);
yystate(48, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,48};
yystate(47, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 10, Tlen);
yystate(47, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 10, Tlen);
yystate(47, Ics, Line, Tlen, _, _) ->
    {10,Tlen,Ics,Line,47};
yystate(46, [76|Ics], Line, Tlen, Action, Alen) ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(46, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,46};
yystate(45, [75|Ics], Line, Tlen, _, _) ->
    yystate(49, Ics, Line, Tlen+1, 38, Tlen);
yystate(45, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(45, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 74 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(45, [C|Ics], Line, Tlen, _, _) when C >= 76, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(45, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,45};
yystate(44, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(48, Ics, Line, Tlen+1, Action, Alen);
yystate(44, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,44};
yystate(43, [84|Ics], Line, Tlen, _, _) ->
    yystate(39, Ics, Line, Tlen+1, 38, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(27, Ics, Line, Tlen+1, 38, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 83 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= 85, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(43, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,43};
yystate(42, [69|Ics], Line, Tlen, Action, Alen) ->
    yystate(38, Ics, Line, Tlen+1, Action, Alen);
yystate(42, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,42};
yystate(41, [67|Ics], Line, Tlen, _, _) ->
    yystate(45, Ics, Line, Tlen+1, 38, Tlen);
yystate(41, [65|Ics], Line, Tlen, _, _) ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(41, [66|Ics], Line, Tlen, _, _) ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 68, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(41, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,41};
yystate(40, [84|Ics], Line, Tlen, Action, Alen) ->
    yystate(44, Ics, Line, Tlen+1, Action, Alen);
yystate(40, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,40};
yystate(39, [79|Ics], Line, Tlen, _, _) ->
    yystate(35, Ics, Line, Tlen+1, 38, Tlen);
yystate(39, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(39, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 78 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(39, [C|Ics], Line, Tlen, _, _) when C >= 80, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(39, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,39};
yystate(38, Ics, Line, Tlen, _, _) ->
    {23,Tlen,Ics,Line};
yystate(37, [65|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 38, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 66, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(37, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,37};
yystate(36, [85|Ics], Line, Tlen, Action, Alen) ->
    yystate(40, Ics, Line, Tlen+1, Action, Alen);
yystate(36, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,36};
yystate(35, [80|Ics], Line, Tlen, _, _) ->
    yystate(31, Ics, Line, Tlen+1, 38, Tlen);
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 79 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= 81, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(35, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,35};
yystate(34, [79|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 38, Tlen);
yystate(34, [73|Ics], Line, Tlen, _, _) ->
    yystate(26, Ics, Line, Tlen+1, 38, Tlen);
yystate(34, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(34, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 72 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(34, [C|Ics], Line, Tlen, _, _) when C >= 74, C =< 78 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(34, [C|Ics], Line, Tlen, _, _) when C >= 80, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(34, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,34};
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 28, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 28, Tlen);
yystate(33, Ics, Line, Tlen, _, _) ->
    {28,Tlen,Ics,Line,33};
yystate(32, [80|Ics], Line, Tlen, Action, Alen) ->
    yystate(36, Ics, Line, Tlen+1, Action, Alen);
yystate(32, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,32};
yystate(31, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 27, Tlen);
yystate(31, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 27, Tlen);
yystate(31, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,31};
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 11, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 11, Tlen);
yystate(30, Ics, Line, Tlen, _, _) ->
    {11,Tlen,Ics,Line,30};
yystate(29, [69|Ics], Line, Tlen, _, _) ->
    yystate(33, Ics, Line, Tlen+1, 38, Tlen);
yystate(29, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(29, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 68 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(29, [C|Ics], Line, Tlen, _, _) when C >= 70, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(29, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,29};
yystate(28, [78|Ics], Line, Tlen, Action, Alen) ->
    yystate(32, Ics, Line, Tlen+1, Action, Alen);
yystate(28, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,28};
yystate(27, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(27, Ics, Line, Tlen+1, 30, Tlen);
yystate(27, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 30, Tlen);
yystate(27, Ics, Line, Tlen, _, _) ->
    {30,Tlen,Ics,Line,27};
yystate(26, [77|Ics], Line, Tlen, _, _) ->
    yystate(22, Ics, Line, Tlen+1, 38, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 76 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 78, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(26, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,26};
yystate(25, [85|Ics], Line, Tlen, _, _) ->
    yystate(29, Ics, Line, Tlen+1, 38, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 84 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 86, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(25, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,25};
yystate(24, Ics, Line, Tlen, _, _) ->
    {19,Tlen,Ics,Line};
yystate(23, [69|Ics], Line, Tlen, _, _) ->
    yystate(19, Ics, Line, Tlen+1, 38, Tlen);
yystate(23, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(23, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 68 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(23, [C|Ics], Line, Tlen, _, _) when C >= 70, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(23, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,23};
yystate(22, [69|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 38, Tlen);
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 68 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= 70, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(22, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,22};
yystate(21, [78|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 38, Tlen);
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 77 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= 79, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(21, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,21};
yystate(20, [69|Ics], Line, Tlen, Action, Alen) ->
    yystate(24, Ics, Line, Tlen+1, Action, Alen);
yystate(20, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,20};
yystate(19, [87|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 38, Tlen);
yystate(19, [65|Ics], Line, Tlen, _, _) ->
    yystate(0, Ics, Line, Tlen+1, 38, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 66, C =< 86 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 88, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(19, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,19};
yystate(18, [78|Ics], Line, Tlen, _, _) ->
    yystate(14, Ics, Line, Tlen+1, 38, Tlen);
yystate(18, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(18, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 77 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(18, [C|Ics], Line, Tlen, _, _) when C >= 79, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(18, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,18};
yystate(17, [73|Ics], Line, Tlen, _, _) ->
    yystate(21, Ics, Line, Tlen+1, 38, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 72 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 74, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(17, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,17};
yystate(16, [80|Ics], Line, Tlen, Action, Alen) ->
    yystate(20, Ics, Line, Tlen+1, Action, Alen);
yystate(16, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,16};
yystate(15, [73|Ics], Line, Tlen, _, _) ->
    yystate(11, Ics, Line, Tlen+1, 38, Tlen);
yystate(15, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(15, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 72 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(15, [C|Ics], Line, Tlen, _, _) when C >= 74, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(15, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,15};
yystate(14, [83|Ics], Line, Tlen, _, _) ->
    yystate(10, Ics, Line, Tlen+1, 38, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 82 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 84, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(14, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,14};
yystate(13, [84|Ics], Line, Tlen, _, _) ->
    yystate(17, Ics, Line, Tlen+1, 38, Tlen);
yystate(13, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(13, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 83 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(13, [C|Ics], Line, Tlen, _, _) when C >= 85, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(13, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,13};
yystate(12, [65|Ics], Line, Tlen, Action, Alen) ->
    yystate(16, Ics, Line, Tlen+1, Action, Alen);
yystate(12, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,12};
yystate(11, [78|Ics], Line, Tlen, _, _) ->
    yystate(7, Ics, Line, Tlen+1, 38, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 77 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 79, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(11, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,11};
yystate(10, [73|Ics], Line, Tlen, _, _) ->
    yystate(6, Ics, Line, Tlen+1, 38, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 72 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 74, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(10, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,10};
yystate(9, [78|Ics], Line, Tlen, _, _) ->
    yystate(13, Ics, Line, Tlen+1, 38, Tlen);
yystate(9, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(9, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 77 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(9, [C|Ics], Line, Tlen, _, _) when C >= 79, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(9, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,9};
yystate(8, [84|Ics], Line, Tlen, Action, Alen) ->
    yystate(12, Ics, Line, Tlen+1, Action, Alen);
yystate(8, [73|Ics], Line, Tlen, Action, Alen) ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(8, [68|Ics], Line, Tlen, Action, Alen) ->
    yystate(68, Ics, Line, Tlen+1, Action, Alen);
yystate(8, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,8};
yystate(7, [68|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 38, Tlen);
yystate(7, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(7, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 67 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(7, [C|Ics], Line, Tlen, _, _) when C >= 69, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(7, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,7};
yystate(6, [79|Ics], Line, Tlen, _, _) ->
    yystate(2, Ics, Line, Tlen+1, 38, Tlen);
yystate(6, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(6, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 78 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(6, [C|Ics], Line, Tlen, _, _) when C >= 80, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(6, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,6};
yystate(5, [79|Ics], Line, Tlen, _, _) ->
    yystate(9, Ics, Line, Tlen+1, 38, Tlen);
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 78 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= 80, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(5, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,5};
yystate(4, [32|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 13, Tlen);
yystate(4, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 13, Tlen);
yystate(4, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 13, Tlen);
yystate(4, Ics, Line, Tlen, _, _) ->
    {13,Tlen,Ics,Line,4};
yystate(3, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 24, Tlen);
yystate(3, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 24, Tlen);
yystate(3, Ics, Line, Tlen, _, _) ->
    {24,Tlen,Ics,Line,3};
yystate(2, [78|Ics], Line, Tlen, _, _) ->
    yystate(1, Ics, Line, Tlen+1, 38, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 77 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 79, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(2, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,2};
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 5, Tlen);
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 5, Tlen);
yystate(1, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line,1};
yystate(0, [68|Ics], Line, Tlen, _, _) ->
    yystate(4, Ics, Line, Tlen+1, 38, Tlen);
yystate(0, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(0, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 67 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(0, [C|Ics], Line, Tlen, _, _) when C >= 69, C =< 90 ->
    yystate(55, Ics, Line, Tlen+1, 38, Tlen);
yystate(0, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,0};
yystate(S, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,S}.

%% yyaction(Action, TokenLength, TokenChars, TokenLine) ->
%% {token,Token} | {end_token, Token} | skip_token | {error,String}.
%% Generated action function.

yyaction(0, _, _, TokenLine) ->
    yyaction_0(TokenLine);
yyaction(1, _, _, TokenLine) ->
    yyaction_1(TokenLine);
yyaction(2, _, _, TokenLine) ->
    yyaction_2(TokenLine);
yyaction(3, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_3(TokenChars, TokenLine);
yyaction(4, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_4(TokenChars, TokenLine);
yyaction(5, _, _, TokenLine) ->
    yyaction_5(TokenLine);
yyaction(6, _, _, TokenLine) ->
    yyaction_6(TokenLine);
yyaction(7, _, _, TokenLine) ->
    yyaction_7(TokenLine);
yyaction(8, _, _, TokenLine) ->
    yyaction_8(TokenLine);
yyaction(9, _, _, TokenLine) ->
    yyaction_9(TokenLine);
yyaction(10, _, _, TokenLine) ->
    yyaction_10(TokenLine);
yyaction(11, _, _, TokenLine) ->
    yyaction_11(TokenLine);
yyaction(12, _, _, TokenLine) ->
    yyaction_12(TokenLine);
yyaction(13, _, _, TokenLine) ->
    yyaction_13(TokenLine);
yyaction(14, _, _, TokenLine) ->
    yyaction_14(TokenLine);
yyaction(15, _, _, TokenLine) ->
    yyaction_15(TokenLine);
yyaction(16, _, _, TokenLine) ->
    yyaction_16(TokenLine);
yyaction(17, _, _, TokenLine) ->
    yyaction_17(TokenLine);
yyaction(18, _, _, TokenLine) ->
    yyaction_18(TokenLine);
yyaction(19, _, _, TokenLine) ->
    yyaction_19(TokenLine);
yyaction(20, _, _, TokenLine) ->
    yyaction_20(TokenLine);
yyaction(21, _, _, TokenLine) ->
    yyaction_21(TokenLine);
yyaction(22, _, _, TokenLine) ->
    yyaction_22(TokenLine);
yyaction(23, _, _, TokenLine) ->
    yyaction_23(TokenLine);
yyaction(24, _, _, TokenLine) ->
    yyaction_24(TokenLine);
yyaction(25, _, _, TokenLine) ->
    yyaction_25(TokenLine);
yyaction(26, _, _, TokenLine) ->
    yyaction_26(TokenLine);
yyaction(27, _, _, TokenLine) ->
    yyaction_27(TokenLine);
yyaction(28, _, _, TokenLine) ->
    yyaction_28(TokenLine);
yyaction(29, _, _, TokenLine) ->
    yyaction_29(TokenLine);
yyaction(30, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_30(TokenChars, TokenLine);
yyaction(31, _, _, TokenLine) ->
    yyaction_31(TokenLine);
yyaction(32, _, _, TokenLine) ->
    yyaction_32(TokenLine);
yyaction(33, _, _, TokenLine) ->
    yyaction_33(TokenLine);
yyaction(34, _, _, TokenLine) ->
    yyaction_34(TokenLine);
yyaction(35, _, _, TokenLine) ->
    yyaction_35(TokenLine);
yyaction(36, _, _, TokenLine) ->
    yyaction_36(TokenLine);
yyaction(37, _, _, _) ->
    yyaction_37();
yyaction(38, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_38(TokenChars, TokenLine);
yyaction(_, _, _, _) -> error.

-compile({inline,yyaction_0/1}).
-file("src/tokens.xrl", 47).
yyaction_0(TokenLine) ->
     { token, { ')', TokenLine } } .

-compile({inline,yyaction_1/1}).
-file("src/tokens.xrl", 48).
yyaction_1(TokenLine) ->
     { token, { '(', TokenLine } } .

-compile({inline,yyaction_2/1}).
-file("src/tokens.xrl", 49).
yyaction_2(TokenLine) ->
     { token, { ',', TokenLine } } .

-compile({inline,yyaction_3/2}).
-file("src/tokens.xrl", 50).
yyaction_3(TokenChars, TokenLine) ->
     { token, { float, TokenLine, TokenChars } } .

-compile({inline,yyaction_4/2}).
-file("src/tokens.xrl", 51).
yyaction_4(TokenChars, TokenLine) ->
     { token, { int, TokenLine, TokenChars } } .

-compile({inline,yyaction_5/1}).
-file("src/tokens.xrl", 54).
yyaction_5(TokenLine) ->
     { token, { 'DIMENSION', TokenLine } } .

-compile({inline,yyaction_6/1}).
-file("src/tokens.xrl", 55).
yyaction_6(TokenLine) ->
     { token, { 'EQUIVALENCE', TokenLine } } .

-compile({inline,yyaction_7/1}).
-file("src/tokens.xrl", 56).
yyaction_7(TokenLine) ->
     { token, { 'IF', TokenLine } } .

-compile({inline,yyaction_8/1}).
-file("src/tokens.xrl", 57).
yyaction_8(TokenLine) ->
     { token, { 'GO TO', TokenLine } } .

-compile({inline,yyaction_9/1}).
-file("src/tokens.xrl", 58).
yyaction_9(TokenLine) ->
     { token, { 'ASSIGN', TokenLine } } .

-compile({inline,yyaction_10/1}).
-file("src/tokens.xrl", 59).
yyaction_10(TokenLine) ->
     { token, { 'TO', TokenLine } } .

-compile({inline,yyaction_11/1}).
-file("src/tokens.xrl", 60).
yyaction_11(TokenLine) ->
     { token, { 'DO', TokenLine } } .

-compile({inline,yyaction_12/1}).
-file("src/tokens.xrl", 61).
yyaction_12(TokenLine) ->
     { token, { 'FORMAT', TokenLine } } .

-compile({inline,yyaction_13/1}).
-file("src/tokens.xrl", 62).
yyaction_13(TokenLine) ->
     { token, { 'READ', TokenLine } } .

-compile({inline,yyaction_14/1}).
-file("src/tokens.xrl", 63).
yyaction_14(TokenLine) ->
     { token, { 'READ INPUT TAPE', TokenLine } } .

-compile({inline,yyaction_15/1}).
-file("src/tokens.xrl", 64).
yyaction_15(TokenLine) ->
     { token, { 'WRITE', TokenLine } } .

-compile({inline,yyaction_16/1}).
-file("src/tokens.xrl", 65).
yyaction_16(TokenLine) ->
     { token, { 'WRITE OUTPUT TAPE', TokenLine } } .

-compile({inline,yyaction_17/1}).
-file("src/tokens.xrl", 66).
yyaction_17(TokenLine) ->
     { token, { 'PRINT', TokenLine } } .

-compile({inline,yyaction_18/1}).
-file("src/tokens.xrl", 67).
yyaction_18(TokenLine) ->
     { token, { 'PUNCH', TokenLine } } .

-compile({inline,yyaction_19/1}).
-file("src/tokens.xrl", 68).
yyaction_19(TokenLine) ->
     { token, { 'READ TAPE', TokenLine } } .

-compile({inline,yyaction_20/1}).
-file("src/tokens.xrl", 69).
yyaction_20(TokenLine) ->
     { token, { 'READ DRUM', TokenLine } } .

-compile({inline,yyaction_21/1}).
-file("src/tokens.xrl", 70).
yyaction_21(TokenLine) ->
     { token, { 'WRITE TAPE', TokenLine } } .

-compile({inline,yyaction_22/1}).
-file("src/tokens.xrl", 71).
yyaction_22(TokenLine) ->
     { token, { 'WRITE DRUM', TokenLine } } .

-compile({inline,yyaction_23/1}).
-file("src/tokens.xrl", 72).
yyaction_23(TokenLine) ->
     { token, { 'END FILE', TokenLine } } .

-compile({inline,yyaction_24/1}).
-file("src/tokens.xrl", 73).
yyaction_24(TokenLine) ->
     { token, { 'REWIND', TokenLine } } .

-compile({inline,yyaction_25/1}).
-file("src/tokens.xrl", 74).
yyaction_25(TokenLine) ->
     { token, { 'BACKSPACE', TokenLine } } .

-compile({inline,yyaction_26/1}).
-file("src/tokens.xrl", 75).
yyaction_26(TokenLine) ->
     { token, { 'PAUSE', TokenLine } } .

-compile({inline,yyaction_27/1}).
-file("src/tokens.xrl", 76).
yyaction_27(TokenLine) ->
     { token, { 'STOP', TokenLine } } .

-compile({inline,yyaction_28/1}).
-file("src/tokens.xrl", 77).
yyaction_28(TokenLine) ->
     { token, { 'CONTINUE', TokenLine } } .

-compile({inline,yyaction_29/1}).
-file("src/tokens.xrl", 78).
yyaction_29(TokenLine) ->
     { token, { 'FREQUENCY', TokenLine } } .

-compile({inline,yyaction_30/2}).
-file("src/tokens.xrl", 80).
yyaction_30(TokenChars, TokenLine) ->
     { token, { 'STATEMENT', TokenLine, TokenChars } } .

-compile({inline,yyaction_31/1}).
-file("src/tokens.xrl", 82).
yyaction_31(TokenLine) ->
     { token, { '=', TokenLine } } .

-compile({inline,yyaction_32/1}).
-file("src/tokens.xrl", 83).
yyaction_32(TokenLine) ->
     { token, { '+', TokenLine } } .

-compile({inline,yyaction_33/1}).
-file("src/tokens.xrl", 84).
yyaction_33(TokenLine) ->
     { token, { '*', TokenLine } } .

-compile({inline,yyaction_34/1}).
-file("src/tokens.xrl", 85).
yyaction_34(TokenLine) ->
     { token, { '/', TokenLine } } .

-compile({inline,yyaction_35/1}).
-file("src/tokens.xrl", 86).
yyaction_35(TokenLine) ->
     { token, { '-', TokenLine } } .

-compile({inline,yyaction_36/1}).
-file("src/tokens.xrl", 87).
yyaction_36(TokenLine) ->
     { token, { newline, TokenLine } } .

-compile({inline,yyaction_37/0}).
-file("src/tokens.xrl", 89).
yyaction_37() ->
     skip_token .

-compile({inline,yyaction_38/2}).
-file("src/tokens.xrl", 91).
yyaction_38(TokenChars, TokenLine) ->
     { token, { identifier, TokenLine, TokenChars } } .

-file("/Users/jake/erlinstalls/19.0/lib/parsetools-2.1.2/include/leexinc.hrl", 290).
